// Generates app/ui/tokens.slint and extension/src/tokens.css from design/tokens.json.
// Usage: node scripts/gen-tokens.mjs [--check]   (--check fails if the outputs are stale)
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(join(root, "design/tokens.json"), "utf8"));
const check = process.argv.includes("--check");
const header = "Generated by scripts/gen-tokens.mjs from design/tokens.json. Do not edit.";

const { dark, light } = tokens.colors;
const colorNames = Object.keys(dark);
for (const [a, b, name] of [[dark, light, "light"], [light, dark, "dark"]]) {
  const missing = Object.keys(a).filter((k) => !(k in b));
  if (missing.length) throw new Error(`${name} theme is missing: ${missing.join(", ")}`);
}
for (const [name, value] of Object.entries({ ...dark, ...light })) {
  if (!/^#([0-9a-f]{6}|[0-9a-f]{8})$/i.test(value)) throw new Error(`bad color ${name}: ${value}`);
}

const slint = [
  `// ${header}`,
  "",
  "export global Theme {",
  "    in-out property <bool> dark: true;",
  "",
  ...colorNames.map((n) => `    out property <color> ${n}: dark ? ${dark[n]} : ${light[n]};`),
  "",
  // Slint takes one family; the rest of the stack is for the extension.
  ...Object.entries(tokens.fonts).map(([n, stack]) => `    out property <string> font-${n}: "${stack[0]}";`),
  "",
  ...Object.entries(tokens.metrics).map(([n, v]) => `    out property <length> ${n}: ${v}px;`),
  "",
  ...Object.entries(tokens.durations).map(([n, v]) => `    out property <duration> duration-${n}: ${v}ms;`),
  "}",
  "",
].join("\n");

const fontStack = (stack) =>
  stack.map((f) => (/^[a-z-]+$/.test(f) ? f : `'${f}'`)).join(", ");
const block = (selector, lines) => [`${selector} {`, ...lines.map((l) => `  ${l}`), "}"].join("\n");

const css = [
  `/* ${header} */`,
  "",
  block(":root,\n[data-theme=\"dark\"]", colorNames.map((n) => `--color-${n}: ${dark[n]};`)),
  "",
  block("[data-theme=\"light\"]", colorNames.map((n) => `--color-${n}: ${light[n]};`)),
  "",
  block(":root", [
    ...Object.entries(tokens.fonts).map(([n, s]) => `--font-${n}: ${fontStack(s)};`),
    ...Object.entries(tokens.metrics).map(([n, v]) => `--${n}: ${v}px;`),
    ...Object.entries(tokens.durations).map(([n, v]) => `--duration-${n}: ${v}ms;`),
  ]),
  "",
  "@media (prefers-reduced-motion: reduce) {",
  "  :root {",
  ...Object.keys(tokens.durations).map((n) => `    --duration-${n}: 0ms;`),
  "  }",
  "}",
  "",
].join("\n");

let stale = [];
for (const [rel, text] of [["app/ui/tokens.slint", slint], ["extension/src/tokens.css", css]]) {
  const path = join(root, rel);
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === text) continue;
  if (check) {
    stale.push(rel);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text);
    console.log(`wrote ${rel}`);
  }
}
if (stale.length) {
  console.error(`stale generated files: ${stale.join(", ")} — run node scripts/gen-tokens.mjs`);
  process.exit(1);
}
